package com.lanxinai.data.paltform.ducklake.service;

import com.lanxinai.data.paltform.ducklake.config.DemoSchemaManager;
import com.lanxinai.data.paltform.ducklake.dao.DaoKind;
import com.lanxinai.data.paltform.ducklake.dao.DemoRecordDao;
import com.lanxinai.data.paltform.ducklake.domain.DemoRecord;
import com.lanxinai.data.paltform.ducklake.dto.BatchOperationResponse;
import com.lanxinai.data.paltform.ducklake.dto.ScenarioResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.TimeUnit;
import java.util.stream.IntStream;

@Service
public class DuckLakeDemoService {

    private static final Logger log = LoggerFactory.getLogger(DuckLakeDemoService.class);
    private static final int MAX_BATCH_SIZE = 1_000;

    private final DemoSchemaManager schemaManager;
    private final Map<DaoKind, DemoRecordDao> daos;

    public DuckLakeDemoService(DemoSchemaManager schemaManager, List<DemoRecordDao> daoImplementations) {
        this.schemaManager = schemaManager;
        this.daos = new EnumMap<>(DaoKind.class);
        daoImplementations.forEach(dao -> this.daos.put(dao.kind(), dao));
    }

    public Map<String, Object> initializeTable() {
        schemaManager.initialize();
        log.info("手动初始化测试表完成：{}", schemaManager.qualifiedTableName());
        return Map.of(
                "initialized", true,
                "table", schemaManager.qualifiedTableName(),
                "primaryKeyNote", "DuckLake does not enforce primary keys; UUID values are generated by the application"
        );
    }

    public List<DemoRecord> findAll(String daoName, int limit) {
        DemoRecordDao dao = dao(daoName);
        List<DemoRecord> rows = dao.findAll(validateRange(limit, 1, 10_000, "limit"));
        log.info("查询完成：dao={}，返回 {} 条", dao.kind().pathValue(), rows.size());
        return rows;
    }

    public long count(String daoName) {
        DemoRecordDao dao = dao(daoName);
        long total = dao.count();
        log.info("计数完成：dao={}，total={}", dao.kind().pathValue(), total);
        return total;
    }

    public BatchOperationResponse insert(String daoName, int numberOfRows) {
        long started = System.nanoTime();
        DemoRecordDao dao = dao(daoName);
        int count = validateBatchSize(numberOfRows);
        String batchId = dao.kind().pathValue() + "-" + UUID.randomUUID();
        LocalDateTime now = LocalDateTime.now(ZoneOffset.UTC);
        List<DemoRecord> rows = IntStream.range(0, count)
                .mapToObj(index -> new DemoRecord(
                        UUID.randomUUID().toString(),
                        batchId,
                        "demo-" + dao.kind().pathValue() + "-" + index,
                        index + 1,
                        BigDecimal.valueOf(100L + index).setScale(2),
                        "NEW",
                        "inserted by " + dao.kind().pathValue(),
                        now.plusNanos(index),
                        now.plusNanos(index)
                ))
                .toList();
        int affected = dao.insertBatch(rows);
        BatchOperationResponse response = response(dao, "insert", batchId, count, affected);
        logOperation(response, started);
        return response;
    }

    public BatchOperationResponse update(String daoName, String batchId, int numberOfRows, String suffix) {
        long started = System.nanoTime();
        DemoRecordDao dao = dao(daoName);
        int count = validateBatchSize(numberOfRows);
        String safeSuffix = validateSuffix(suffix);
        int affected = dao.updateFirstN(requireBatchId(batchId), count, safeSuffix);
        BatchOperationResponse response = response(dao, "update", batchId, count, affected);
        logOperation(response, started);
        return response;
    }

    public BatchOperationResponse delete(String daoName, String batchId, int numberOfRows) {
        long started = System.nanoTime();
        DemoRecordDao dao = dao(daoName);
        int count = validateBatchSize(numberOfRows);
        int affected = dao.deleteFirstN(requireBatchId(batchId), count);
        BatchOperationResponse response = response(dao, "delete", batchId, count, affected);
        logOperation(response, started);
        return response;
    }

    public ScenarioResponse scenario(String daoName, int insertN, int updateN, int deleteN) {
        long started = System.nanoTime();
        DemoRecordDao dao = dao(daoName);
        // 场景只操作本次生成的 batchId，不会修改其他用户或历史批次的数据。
        long before = dao.count();
        BatchOperationResponse inserted = insert(daoName, insertN);
        long afterInsert = dao.count();
        BatchOperationResponse updated = update(daoName, inserted.batchId(), updateN, "-updated");
        long afterUpdate = dao.count();
        BatchOperationResponse deleted = delete(daoName, inserted.batchId(), deleteN);
        long afterDelete = dao.count();
        List<DemoRecord> remaining = dao.findByBatchId(inserted.batchId(), MAX_BATCH_SIZE);
        ScenarioResponse response = new ScenarioResponse(
                dao.kind().pathValue(), inserted.batchId(), inserted.affected(), updated.affected(), deleted.affected(),
                before, afterInsert, afterUpdate, afterDelete, remaining, Instant.now()
        );
        long elapsedMs = TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - started);
        log.info("完整 CRUD 场景完成：dao={}，batchId={}，inserted={}，updated={}，deleted={}，remaining={}，耗时 {} ms",
                response.dao(), response.batchId(), response.inserted(), response.updated(), response.deleted(),
                response.remainingRows().size(), elapsedMs);
        return response;
    }

    private BatchOperationResponse response(DemoRecordDao dao, String operation, String batchId,
                                            int requested, int affected) {
        return new BatchOperationResponse(
                dao.kind().pathValue(), operation, batchId, requested, affected, dao.count(),
                dao.findByBatchId(batchId, MAX_BATCH_SIZE), Instant.now()
        );
    }

    private void logOperation(BatchOperationResponse response, long started) {
        long elapsedMs = TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - started);
        log.info("DuckLake {} 完成：dao={}，batchId={}，requested={}，affected={}，total={}，耗时 {} ms",
                response.operation(), response.dao(), response.batchId(), response.requested(), response.affected(),
                response.totalRows(), elapsedMs);
    }

    private DemoRecordDao dao(String name) {
        DemoRecordDao dao = daos.get(DaoKind.fromPath(name));
        if (dao == null) {
            throw new IllegalStateException("DAO implementation is not registered: " + name);
        }
        return dao;
    }

    private static int validateBatchSize(int value) {
        return validateRange(value, 1, MAX_BATCH_SIZE, "n");
    }

    private static int validateRange(int value, int min, int max, String name) {
        if (value < min || value > max) {
            throw new IllegalArgumentException(name + " must be between " + min + " and " + max);
        }
        return value;
    }

    private static String requireBatchId(String batchId) {
        if (batchId == null || batchId.isBlank() || batchId.length() > 128) {
            throw new IllegalArgumentException("batchId is required and must be at most 128 characters");
        }
        return batchId;
    }

    private static String validateSuffix(String suffix) {
        if (suffix == null || suffix.isBlank() || suffix.length() > 32) {
            throw new IllegalArgumentException("suffix is required and must be at most 32 characters");
        }
        return suffix;
    }
}
